name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - name: Setup DigitalOcean SSH 
        uses: fifsky/ssh-action@V0.1.3
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          # username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          # script:
          #   mkdir test
          #   cd test
          #   git clone git@github.com:KivutiBrian/learn-github-actions.git 
          #   echo 'Deployment successfully'
    
          