name: learn-github-actions
# controls when the action will run. Triger the workflow on push
on:
  push:
    branches: [master]

#  workflow is made up of one or more jobs that can run
#  sequentially or in parallel
jobs:

  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout/@v2
      - name: set up python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest tests/test_basic.py

  deploy:
    needs: [test]
    # the type of runner that the job will run on
    runs-on: ubuntu-18.04

    # represent a sequence of tasks that will be executed as part of the
    # job
    steps: 
      - name: Setup DigitalOcean SSH 
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd test-flask-app
            cd app
            git pull origin master  
            docker-compose up --build -d          
          