name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy Flask app 
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.HOST }} #server ip
          key: ${{ secrets.SSH_KEY }} #private or public key of server
          username: ${{ secrets.USERNAME }} #username of the server
          
          script: |
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git .
            echo 'Deployment successful'