name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          pass: ${{secrets.SSH_KEY}}
      - run: |
          mkdir test

          # script: 
          #   mkdir test
          #   cd test
          #   git clone git@github.com:KivutiBrian/learn-github-actions.git 
          #   echo 'Deployment successful'