name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{secrets.HOST}} #server ip
          USERNAME: ${{secrets.USERNAME}} #username of the server
          PORT: ${{secrets.PORT}}
          KEY: ${{secrets.SSH_KEY}} #private or public key of server
          script: 
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git 
            echo 'Deployment successful'