name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Setup DigitalOcean SSH 
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: ${{secrets.HOST}}
          private-key: ${{ secrets.SSH_KEY }}
      -name: Create a folder
        run: mkdir test
          # commands:
          #   mkdir test
          #   cd test
          #   git clone git@github.com:KivutiBrian/learn-github-actions.git 
          #   echo 'Deployment successful'
    
          