name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: fifsky/ssh-action@master
        with:
          command: | 
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git 
            echo 'Deployment successful'
            
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          key: ${{secrets.SSH_KEY}}
    
          