name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: appleboy/scp-action@master
        with:
          HOST: ${{secrets.HOST}} #server ip
          KEY: ${{secrets.SSH_KEY}} #private or public key of server
          USERNAME: ${{secrets.USERNAME}} #username of the server
          
          script: 
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git .
            echo 'Deployment successful'