name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Setup DigitalOcean SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEA4dNKjjcdVjgVPikMKzNkis8geY3bqq9mzOBqSJRGQkCdWy861Hpk
IQwugU9voPAauykOgDTd0YNXknmPAm1B9+E4F0nyxaWTEw2/DLOxNwYcNR+fC1JIbtjRxc
EMYFpuL54SfuqAk4GEXSMRN3SjTnOsK106/msf0mUy9fpWcImWx9PHNYNYHstClJmbyCxc
2xi6y2XGM6dpKUdRwgaRkBCdTFIFLOF6kHpPrenjPaKnlNnBC1sJlI8M41DDF9E9Qrneds
Ea44CieSARQ+7Gh8Cta+yD0RH8cbHK4Whh2XqxlSVujeDMfCkzkDK6Cchl9bZkOOAQ4/kx
qkItuvoPNYK0BwyMAbtK6jnGh2ir0qx3Hd1W7Kob7TbuVqDHrB+NwqRM9OFWpjG95jkrDx
HMpiz8WIF5Z2Ms6MfCycwtLP0Lfc3s4JzX68+2u/6cKbMfykH3rVgHZQW+SZ5eCl/KDln5
08tmDghUKoeAVZYmj3XrP0+W0tf4376f27JZsvYDAAAFkPYOuW32DrltAAAAB3NzaC1yc2
EAAAGBAOHTSo43HVY4FT4pDCszZIrPIHmN26qvZszgakiURkJAnVsvOtR6ZCEMLoFPb6Dw
GrspDoA03dGDV5J5jwJtQffhOBdJ8sWlkxMNvwyzsTcGHDUfnwtSSG7Y0cXBDGBabi+eEn
7qgJOBhF0jETd0o05zrCtdOv5rH9JlMvX6VnCJlsfTxzWDWB7LQpSZm8gsXNsYustlxjOn
aSlHUcIGkZAQnUxSBSzhepB6T63p4z2ip5TZwQtbCZSPDONQwxfRPUK53nbBGuOAonkgEU
PuxofArWvsg9ER/HGxyuFoYdl6sZUlbo3gzHwpM5AyugnIZfW2ZDjgEOP5MapCLbr6DzWC
tAcMjAG7Suo5xodoq9Ksdx3dVuyqG+027lagx6wfjcKkTPThVqYxveY5Kw8RzKYs/FiBeW
djLOjHwsnMLSz9C33N7OCc1+vPtrv+nCmzH8pB961YB2UFvkmeXgpfyg5Z+dPLZg4IVCqH
gFWWJo916z9PltLX+N++n9uyWbL2AwAAAAMBAAEAAAGAFUKpMD5sGqPpDBMdPCv4eUEK06
bRWX5t9TfjibW775zZs638oehr6NiWwEHURpiUS66P2O4hPApbgkTDe/0BSu7/MuIZYxY1
hIO0yuNX+dAvc6jodk5m11i+VxnXqnKZEQ6WuzAkrr5w0bvtcQUgItCtEuASH8XCFzLD23
iYDrxFX8bGaHlXIH8OY6MakXvrugzX+TI5uL84HVTDk7q+lYua44aNSi5oNZXuTndIl5Lq
qA7gJ8uIWV4mXnhKBcIDDzCzat+s9+jyIq1FVVqYnG7PuQSZnVVK0yuupue9ySG80opjCU
zL9oZYrgimkrtxsR+EUgF7igd37YsLfolj4HIFTDTau8uXwzhReiJ7lVspVSiuelXdebZf
QVVe0VhULAVe5orr1MVvGNYFRdc2de8CQlaYJM315zOqw/Hpop/McHr+p6CG3lf9s1t8KO
AIxOncK9S0zYrWe55ETRfIre/vDOeCflfL5dJAp5vYXN5DpKK4/WiLrtBmpplZDJGBAAAA
wQC9Jg0PbhGr3Th2wO2GGSm2a7/LZyeEYxT8friIfz2ZPcBw013XgN49a0RzbQzzCOn2Qh
pGvYU8rHGi2jw5isavNSVm6iD/1I9gCizxm2Q0+tG2E+jvQiuaxIDyTM7OwtvoY6MgOyLu
Ao5v/lvl4ZCp3u66x5R3k34UYDSECs6ypg6SdGN6z0e3orYo62PNwjdf7FBAV295SGalBA
D0/P4Pg8TnG4mphCvBi97zKWZ6GemrxcajPQOy1LOvhDUk+30AAADBAPKq0QnLEwOaUCRc
OhnYlCfcqxCzXluBFTjsb9hJtHt6+AVx4u3Iu+b/JYTJr5fyc270wRndoBHTNDwSkBHZg1
TB4rqy2SjlTpPvGW+lv6RzmpSK/uuuPP5K39dpfayigyKceEnUQFpntfZUoW/dwBhLZ8el
1ehkO2Bvxmh0ZQcJsiJhaDbDmuXtym+OL6TRFwADOxnGrpnb4TVnAU4zmr30+L3lxnlW8r
zzVDBXx8zy9Ml2SQmvkf+Yo+8xlcVWYwAAAMEA7juWsh9yBqfqyPb1AxaHuHTjvjUjDjcx
Y3xWsjifOVcwoRPSgVCF8pbgozZlgHCbyVdG8p9Lv4TB4+W3+72dT58jMTV6uV9BrSux4x
HEcFP30wJdMIS3XkpeAY4VBpPMdPtYXU3hcvy9E3IZxIZwFdP2mEp7m0nY1rJa1H54DFUk
EiyTKNhjUxpum44RjkB7mRfwXsEzhjhiaZLlGfBdNvn/zlfU8clvd8eExrTJcf4riBb5ou
wcjNSvCnWpC6PhAAAAE3Jvb3RAbXVlci1zb2x1dGlvbnMBAgMEBQYH

          script:
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git 
            echo 'Deployment successful'
    
          