name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          privateKey: ${{secrets.SSH_KEY}}
          script: 
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git 
            echo 'Deployment successful'