name: learn-github-actions
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v1
      - name: Deploy Flask app 
        uses: docker://evaneos/ssh-action:0.1.0
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.SSH_KEY}}
          commands:
            mkdir test
            cd test
            git clone git@github.com:KivutiBrian/learn-github-actions.git 
            echo 'Deployment successful'
    
          